@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml


Person(burgerUser, "Burger Backend Customer", "A customer of the Burgher App")

System_Boundary(c1, "Burger Social Platform"){
    Container(burgerApp, "Web Application", ".NET Blazor","Provides all of the burger app functionatity to customers via their web browser")
    Container(burgerMobile, "Mobile App", "Xamarin","Provides all of the burger app functionatity to customers via their mobile device")
    Container(burgerAPI, "API Application", "C# and .NET MVC","Provides burger app functionality via a JSON/HTTPS API")
    ContainerDb(burgerDB, "Relational Database", "SQLite 3")
}

System(googleAPI,"Google Places API", "Provides info about nearby restaurands serving burghers." )

Rel(burgerUser, burgerMobile, "Reviews burger places, uploads pictures, finds restaurants using", "HTTPS")
Rel(burgerUser, burgerApp, "Reviews burger places, uploads pictures, finds restaurants using","HTTPS")

Rel(burgerApp, burgerAPI, "Makes API Calls to","JSON/HTTPS")
Rel(burgerMobile, burgerAPI, "Makes API Calls to","JSON/HTTPS")

Rel(burgerAPI,burgerDB ,"Reads and writes to ","EF Core")
Rel(burgerAPI, googleAPI ,"Makes API Calls to","JSON/HTTPS")
@enduml